version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: arq2020q1
    #   MONGO_INITDB_ROOT_PASSWORD: arq2020q1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: arq2020q1
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: arq2020q1

  insumos-backend:
    image: arq2020-insumos-backend
    restart: always
    ports: 
      - 4000:4000
    depends_on:
      - mongo