version: '2.2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: arq2020q1
    #   MONGO_INITDB_ROOT_PASSWORD: arq2020q1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: arq2020q1
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: arq2020q1

  insumos-backend:
    # docker build -t arq2020-insumos-backend
    # dcompose exec insumos-backend sh
    # artillery run ./artillery/createRequestAndDoSomethingWithIt.yml
    image: arq2020-insumos-backend
    restart: always
    ports: 
      - 4000:4000
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/dev
      - JWT_TOKEN=abc123
      # - NODE_OPTIONS=--max_old_space_size=8048
    cpus: 1.5
    mem_limit: 300mb